import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/Nav/NavBar';
import QueryClientProviderWrapper from './_view/QueryClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <QueryClientProviderWrapper>
          <NavBar />
          {children}
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
